/* SMART-TALLES-ACCESSORY-SEARCH-SAFE-V1 */
(function(){'use strict';
var launcherId='safeAccessorySearchLauncher',modalId='safeAccessorySearchModal',productsCache=null;
function norm(v){return String(v==null?'':v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function money(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function css(){if(document.getElementById('safeAccessorySearchStyle'))return;var s=document.createElement('style');s.id='safeAccessorySearchStyle';s.textContent='#'+modalId+'{position:fixed;inset:0;z-index:99999;background:rgba(3,15,30,.72);display:none;align-items:center;justify-content:center;padding:20px;box-sizing:border-box}#'+modalId+'.open{display:flex}.safe-accessory-box{width:min(1000px,96vw);max-height:90vh;background:#fff;border-radius:18px;box-shadow:0 25px 70px rgba(0,0,0,.35);overflow:hidden;display:flex;flex-direction:column}.safe-accessory-head{padding:18px 20px 12px;display:flex;align-items:center;justify-content:space-between;gap:15px;border-bottom:1px solid #e5eaf0}.safe-accessory-head h3{margin:0;color:#08203b;font-size:20px}.safe-accessory-close{border:0;background:#eef3f7;border-radius:50%;width:38px;height:38px;font-size:24px;cursor:pointer}.safe-accessory-search{padding:14px 20px;border-bottom:1px solid #e5eaf0}.safe-accessory-search input{width:100%;box-sizing:border-box;padding:13px 15px;border:2px solid #dce5ee;border-radius:12px;font-size:16px;outline:none}.safe-accessory-search input:focus{border-color:#19b8e6}.safe-accessory-meta{padding:0 20px 10px;color:#607080;font-size:13px}.safe-accessory-results{overflow:auto;padding:4px 20px 20px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.safe-accessory-card{border:1px solid #dfe7ef;border-radius:14px;padding:12px;display:grid;grid-template-columns:130px 1fr;gap:14px;align-items:center;background:#fff}.safe-accessory-card img{width:130px;height:130px;object-fit:contain;border-radius:10px;background:#f4f7fa}.safe-accessory-info b{display:block;color:#102d49;font-size:15px;line-height:1.25}.safe-accessory-info small{display:block;color:#657789;margin-top:4px}.safe-accessory-price{font-size:18px;font-weight:800;color:#08203b;margin:9px 0}.safe-accessory-add{border:0;border-radius:9px;padding:9px 12px;background:#0b79d0;color:#fff;font-weight:700;cursor:pointer}.safe-accessory-add:disabled{opacity:.5;cursor:not-allowed}.safe-accessory-empty{grid-column:1/-1;padding:30px;text-align:center;color:#657789}.safe-accessory-launcher{margin:14px 0;display:flex;gap:10px;align-items:center;flex-wrap:wrap}.safe-accessory-launcher button{border:0;border-radius:10px;padding:11px 16px;background:#0b79d0;color:#fff;font-weight:700;cursor:pointer}.safe-accessory-launcher span{font-size:13px;color:#647586}@media(max-width:700px){.safe-accessory-results{grid-template-columns:1fr}.safe-accessory-card{grid-template-columns:105px 1fr}.safe-accessory-card img{width:105px;height:105px}}';document.head.appendChild(s)}
function modal(){if(document.getElementById(modalId))return;var m=document.createElement('div');m.id=modalId;m.innerHTML='<div class="safe-accessory-box" role="dialog" aria-modal="true"><div class="safe-accessory-head"><h3>🔎 Pesquisar acessórios</h3><button class="safe-accessory-close" type="button">×</button></div><div class="safe-accessory-search"><input id="safeAccessoryInput" type="search" placeholder="Digite nome, modelo, marca, compatibilidade ou SKU..." autocomplete="off"></div><div class="safe-accessory-meta" id="safeAccessoryMeta">Carregando acessórios...</div><div class="safe-accessory-results" id="safeAccessoryResults"></div></div>';document.body.appendChild(m);m.addEventListener('click',function(e){if(e.target===m)close()});m.querySelector('.safe-accessory-close').addEventListener('click',close);document.getElementById('safeAccessoryInput').addEventListener('input',render);document.addEventListener('keydown',function(e){if(e.key==='Escape')close()})}
function launcher(){if(document.getElementById(launcherId))return;var cat=document.getElementById('categorySelect'),host=document.getElementById('brand')?.closest('label');if(!cat||!host)return;var w=document.createElement('div');w.id=launcherId;w.className='safe-accessory-launcher';w.innerHTML='<button type="button">🔎 Pesquisar acessórios</button><span>Pesquise sem percorrer todo o catálogo.</span>';host.parentNode.insertBefore(w,host.nextSibling);w.querySelector('button').addEventListener('click',open);}
async function get(){if(productsCache)return productsCache;var r=await fetch('/api/products',{headers:{Accept:'application/json'}});if(!r.ok)throw Error('Não foi possível carregar os acessórios.');var a=await r.json();productsCache=a.filter(function(x){return norm(x.category).indexOf('acessor')>=0});return productsCache}
function searchable(x){return [x.model,x.name,x.title,x.brand,x.sku,x.category,x.compatibility,x.compatibilities,x.compatible,x.compatible_with,x.description].map(norm).join(' ')}
async function open(){modal();var m=document.getElementById(modalId);m.classList.add('open');document.getElementById('safeAccessoryResults').innerHTML='<div class="safe-accessory-empty">Carregando acessórios...</div>';try{await get();render();setTimeout(function(){document.getElementById('safeAccessoryInput').focus()},50)}catch(e){document.getElementById('safeAccessoryResults').innerHTML='<div class="safe-accessory-empty">'+esc(e.message)+'</div>'}}
function close(){var m=document.getElementById(modalId);if(m)m.classList.remove('open')}
function render(){if(!productsCache)return;var q=norm(document.getElementById('safeAccessoryInput')?.value||''),a=(q?productsCache.filter(function(x){return searchable(x).indexOf(q)>=0}):productsCache).slice(0,100),meta=document.getElementById('safeAccessoryMeta'),box=document.getElementById('safeAccessoryResults');meta.textContent=q?a.length+' resultado(s) para "'+q+'"':productsCache.length+' acessórios disponíveis';if(!a.length){box.innerHTML='<div class="safe-accessory-empty">Nenhum acessório encontrado.</div>';return}box.innerHTML=a.map(function(x){var n=x.model||x.name||x.title||'Acessório',p=Number(x.price)||0;return '<div class="safe-accessory-card">'+(x.image?'<img src="'+esc(x.image)+'" alt="">':'<div></div>')+'<div class="safe-accessory-info"><b>'+esc(n)+'</b>'+(x.brand?'<small>Marca: '+esc(x.brand)+'</small>':'')+(x.sku?'<small>SKU: '+esc(x.sku)+'</small>':'')+'<div class="safe-accessory-price">'+(p>0?money(p):'Preço não cadastrado')+'</div><button class="safe-accessory-add" data-id="'+esc(x.id)+'" '+(p>0?'':'disabled')+'>＋ Adicionar ao orçamento</button></div></div>'}).join('');box.querySelectorAll('.safe-accessory-add').forEach(function(b){b.addEventListener('click',function(){if(typeof window.chooseProduct!=='function'){alert('A seleção de produto não está disponível.');return}window.chooseProduct(Number(b.dataset.id));setTimeout(function(){var add=document.getElementById('add');if(add)add.click();close()},100)})})}
function sync(){var w=document.getElementById(launcherId),c=document.getElementById('categorySelect');if(w&&c)w.style.display=c.value==='Acessórios'?'flex':'none'}
function init(){css();modal();launcher();sync();var c=document.getElementById('categorySelect');if(c)c.addEventListener('change',sync);var old=window.setCategory;if(typeof old==='function')window.setCategory=function(v){old(v);sync()};setInterval(sync,1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();
